version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - ci_appveyor_mar17
environment:
  PATH: '%PATH%;C:\Program Files\CMake\bin;C:\Python36-x64;C:\Program Files\Java\jdk1.8.0;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;C:\Windows\Microsoft.NET\Framework\v4.0.30319;'
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
build_script:
- cmd: cinst -i -y maven
- cmd: echo %PATH%
- cmd: python build_scripts/indigo-release-libs.py --preset=win64-2015
- cmd: python build_scripts/indigo-release-libs.py --preset=win32-2015
- cmd: python build_scripts/indigo-make-by-libs.py --type=python,java,dotnet
